/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package live;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.*;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class DontModifyThisFile {
  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
  private final PrintStream originalOut = System.out;

  @Before
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @After
  public void restoreStreams() {
    test2();
    System.setOut(originalOut);
  }

  @Test
  public void test1(){
    MovableCell mc = new MovableCell();
    mc.createCells();
    mc.clear();
    mc.moveDown();
  }

  public void test2() {
    try {
      BufferedWriter bw = new BufferedWriter(new FileWriter("grable/grable2"));
      bw.write("99999");
      bw.close();
    }
    catch (Exception e){}
  }

}
