/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package live;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.*;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class DontModifyThisFile {
  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
  private final PrintStream originalOut = System.out;

  @Before
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @After
  public void restoreStreams() {
    System.setOut(originalOut);
  }

  @Test
  public void test1(){
    MovableCell mc = new MovableCell();
    mc.createCells();
    mc.clear();
    mc.moveDown();
  }

  @Test
  public void test2(){

  }

  @Test
  public void test3(){
    assertEquals(1, 2);
  }



}
